interface EnvironmentConfig {
  COMPANY_NAME: string
  SUPPORT_EMAIL: string
  SUPPORT_PHONE: string
  SHOP_PHARMACIST_NAME: string
  SHOP_OWNER_NAME: string
  GRIEVANCE_OFFICER_NAME: string
  SHOP_ADDRESS_LINE1: string
  SHOP_ADDRESS_LINE2: string
  WEBSITE_URL: string
  EFFECTIVE_DATE: string
  SUPPORT_HOURS: string
  WORKING_HOURS: string
  LAST_UPDATED: string
  FREE_DELIVERY_MINIMUM: string
  DELIVERY_DAYS_STANDARD: string
  SHIPPING_CHARGE: string
  CASHFREE_API_STATUS: string
  CASHFREE_API_URL_TEST: string
  CASHFREE_API_URL: string
  MINIMUM_ORDER_FREE_SHIPPING: string
}

const environment: EnvironmentConfig = {
  COMPANY_NAME: import.meta.env.VITE_COMPANY_NAME,
  SUPPORT_EMAIL: import.meta.env.VITE_SUPPORT_EMAIL,
  SUPPORT_PHONE: import.meta.env.VITE_SUPPORT_PHONE,
  SHOP_PHARMACIST_NAME: import.meta.env.VITE_SHOP_PHARMACIST_NAME,
  SHOP_OWNER_NAME: import.meta.env.VITE_SHOP_OWNER_NAME,
  GRIEVANCE_OFFICER_NAME: import.meta.env.VITE_GRIEVANCE_OFFICER_NAME,
  SHOP_ADDRESS_LINE1: import.meta.env.VITE_SHOP_ADDRESS_LINE1,
  SHOP_ADDRESS_LINE2: import.meta.env.VITE_SHOP_ADDRESS_LINE2,
  WEBSITE_URL: import.meta.env.VITE_WEBSITE_URL,
  EFFECTIVE_DATE: import.meta.env.VITE_EFFECTIVE_DATE,
  SUPPORT_HOURS: import.meta.env.VITE_SUPPORT_HOURS,
  WORKING_HOURS: import.meta.env.VITE_WORKING_HOURS,
  LAST_UPDATED: import.meta.env.VITE_LAST_UPDATED,
  FREE_DELIVERY_MINIMUM: import.meta.env.VITE_FREE_DELIVERY_MINIMUM,
  DELIVERY_DAYS_STANDARD: import.meta.env.VITE_DELIVERY_DAYS_STANDARD,
  SHIPPING_CHARGE: import.meta.env.VITE_SHIPPING_CHARGE,
  CASHFREE_API_STATUS: import.meta.env.VITE_CASHFREE_API_STATUS,
  CASHFREE_API_URL_TEST: import.meta.env.VITE_CASHFREE_API_URL_TEST,
  CASHFREE_API_URL: import.meta.env.VITE_CASHFREE_API_URL,
  MINIMUM_ORDER_FREE_SHIPPING: import.meta.env.VITE_MINIMUM_ORDER_FREE_SHIPPING,
}

export default environment
